# Contains accepted input countries and respective validated version...
country_dict = {
  'AW': 'Aruba',
  'AF': 'Afghanistan',
  'AO': 'Angola',
  'AI': 'Anguilla',
  'AX': 'Åland Islands',
  'AL': 'Albania',
  'AD': 'Andorra',
  'AE': 'United Arab Emirates',
  'AR': 'Argentina',
  'AM': 'Armenia',
  'AS': 'Samoa',
  'AQ': 'Antarctica',
  'TF': 'French Southern Territories',
  'AG': 'Antigua and Barbuda',
  'AU': 'Australia',
  'AT': 'Austria',
  'AZ': 'Azerbaijan',
  'BI': 'Burundi',
  'BE': 'Belgium',
  'BJ': 'Benin',
  'BQ': 'Bonaire',
  'BF': 'Burkina',
  'BD': 'Bangladesh',
  'BG': 'Bulgaria',
  'BH': 'Bahrain',
  'BS': 'Bahamas',
  'BA': 'Bosnia and Herzegovina',
  'BL': 'Saint Barts',
  'BY': 'Belarus',
  'BZ': 'Belize',
  'BM': 'Bermuda',
  'BO': 'Bolivia',
  'BR': 'Brazil',
  'BB': 'Barbados',
  'BN': 'Brunei',
  'BT': 'Bhutan',
  'BV': 'Bouvet Island',
  'BW': 'Botswana',
  'CF': 'Central African Republic',
  'CA': 'Canada',
  'CC': 'Cocos (Keeling) Islands',
  'CH': 'Switzerland',
  'CL': 'Chile',
  'CN': 'China',
  'CI': 'Ivory Coast',
  'CM': 'Cameroon',
  'CD': 'Congo',
  'CG': 'Congo',
  'CK': 'Cook Islands',
  'CO': 'Colombia',
  'KM': 'Comoros',
  'CV': 'Cape Verde',
  'CR': 'Costa Rica',
  'CU': 'Cuba',
  'CW': 'Curacao',
  'CX': 'Christmas Island',
  'KY': 'Cayman Islands',
  'CY': 'Cyprus',
  'CZ': 'Czechia',
  'DE': 'Germany',
  'DJ': 'Djibouti',
  'DM': 'Dominica',
  'DK': 'Denmark',
  'DO': 'Dominican Republic',
  'DZ': 'Algeria',
  'EC': 'Ecuador',
  'EG': 'Egypt',
  'ER': 'Eritrea',
  'EH': 'Western Sahara',
  'ES': 'Spain',
  'EE': 'Estonia',
  'ET': 'Ethiopia',
  'FI': 'Finland',
  'FJ': 'Fiji',
  'FK': 'Falkland Islands',
  'FR': 'France',
  'FO': 'Faroe Islands',
  'FM': 'Micronesia',
  'GA': 'Gabon',
  'GB': 'United Kingdom',
  'GE': 'Georgia',
  'GG': 'Guernsey',
  'GH': 'Ghana',
  'GI': 'Gibraltar',
  'GN': 'Guinea',
  'GP': 'Guadeloupe',
  'GM': 'Gambia',
  'GW': 'Guinea-Bissau',
  'GQ': 'Equatorial Guinea',
  'GR': 'Greece',
  'GD': 'Grenada',
  'GL': 'Greenland',
  'GT': 'Guatemala',
  'GF': 'French Guiana',
  'GU': 'Guam',
  'GY': 'Guyana',
  'HK': 'Hong Kong',
  'HM': 'Australia',
  'HN': 'Honduras',
  'HR': 'Croatia',
  'HT': 'Haiti',
  'HU': 'Hungary',
  'ID': 'Indonesia',
  'IM': 'Isle of Man',
  'IN': 'India',
  'IO': 'British Indian Ocean Territory',
  'IE': 'Ireland',
  'IR': 'Iran',
  'IQ': 'Iraq',
  'IS': 'Iceland',
  'IL': 'Israel',
  'IT': 'Italy',
  'JM': 'Jamaica',
  'JE': 'Jersey',
  'JO': 'Jordan',
  'JP': 'Japan',
  'KZ': 'Kazakhstan',
  'KE': 'Kenya',
  'KG': 'Kyrgyzstan',
  'KH': 'Cambodia',
  'KI': 'Kiribati',
  'KN': 'Saint Kitts and Nevis',
  'KR': 'South Korea',
  'KW': 'Kuwait',
  'LA': 'Laos',
  'LB': 'Lebanon',
  'LR': 'Liberia',
  'LY': 'Libya',
  'LC': 'Saint Lucia',
  'LI': 'Liechtenstein',
  'LK': 'Sri Lanka',
  'LS': 'Lesotho',
  'LT': 'Lithuania',
  'LU': 'Luxembourg',
  'LV': 'Latvia',
  'MO': 'Macao',
  'MF': 'Saint Martin',
  'MA': 'Morocco',
  'MC': 'Monaco',
  'MD': 'Moldova',
  'MG': 'Madagascar',
  'MV': 'Maldives',
  'MX': 'Mexico',
  'MH': 'Marshall Islands',
  'MK': 'Macedonia',
  'ML': 'Mali',
  'MT': 'Malta',
  'MM': 'Myanmar',
  'ME': 'Montenegro',
  'MN': 'Mongolia',
  'MP': 'Northern Mariana Islands',
  'MZ': 'Mozambique',
  'MR': 'Mauritania',
  'MS': 'Montserrat',
  'MQ': 'Martinique',
  'MU': 'Mauritius',
  'MW': 'Malawi',
  'MY': 'Malaysia',
  'YT': 'Mayotte',
  'NA': 'Namibia',
  'NC': 'New Caledonia',
  'NE': 'Niger',
  'NF': 'Norfolk Island',
  'NG': 'Nigeria',
  'NI': 'Nicaragua',
  'NU': 'Niue',
  'NL': 'Netherlands',
  'NO': 'Norway',
  'NP': 'Nepal',
  'NR': 'Nauru',
  'NZ': 'New Zealand',
  'OM': 'Oman',
  'PK': 'Pakistan',
  'PA': 'Panama',
  'PN': 'United Kingdom',
  'PE': 'Peru',
  'PH': 'Philippines',
  'PW': 'Palau',
  'PG': 'Papua New Guinea',
  'PL': 'Poland',
  'PR': 'United States',
  'KP': 'South Korea',
  'PT': 'Portugal',
  'PY': 'Paraguay',
  'PS': 'Palestine',
  'PF': 'French Polynesia',
  'QA': 'Qatar',
  'RE': 'Reunion',
  'RO': 'Romania',
  'RU': 'Russia',
  'RW': 'Rwanda',
  'SA': 'Saudi Arabia',
  'SD': 'Sudan',
  'SN': 'Senegal',
  'SG': 'Singapore',
  'GS': 'South Georgia and the South Sandwich Islands',
  'SH': 'Saint Helena',
  'SJ': 'Norway',
  'SB': 'Solomon Islands',
  'SL': 'Sierra Leone',
  'SV': 'El Salvador',
  'SM': 'San Marino',
  'SO': 'Somalia',
  'PM': 'Saint Pierre and Miquelon',
  'RS': 'Serbia',
  'SS': 'South Sudan',
  'ST': 'Sao Tome and Principe',
  'SR': 'Suriname',
  'SK': 'Slovakia',
  'SI': 'Slovenia',
  'SE': 'Sweden',
  'SZ': 'Swaziland',
  'SX': 'Saint Martin',
  'SC': 'Seychelles',
  'SY': 'Syria',
  'TC': 'Turks & Caicos',
  'TD': 'Chad',
  'TG': 'Togo',
  'TH': 'Thailand',
  'TJ': 'Tajikistan',
  'TK': 'Tokelau',
  'TM': 'Turkmenistan',
  'TL': 'East Timor',
  'TO': 'Tonga',
  'TT': 'Trinidad and Tobago',
  'TN': 'Tunisia',
  'TR': 'Turkey',
  'TV': 'Tuvalu',
  'TW': 'Taiwan',
  'TZ': 'Tanzania',
  'UG': 'Uganda',
  'UA': 'Ukraine',
  'UM': 'United States',
  'UY': 'Uruguay',
  'US': 'United States',
  'UZ': 'Uzbekistan',
  'VA': 'Vatican City',
  'VC': 'Saint Vincent and the Grenadines',
  'VE': 'Venezuela',
  'VG': 'US Virgin Islands',
  'VI': 'US Virgin Islands',
  'VN': 'Vietnam',
  'VU': 'Vanuatu',
  'WF': 'France',
  'WS': 'Samoa',
  'YE': 'Yemen',
  'ZA': 'South Africa',
  'ZM': 'Zambia',
  'ZW': 'Zimbabwe',
  'ABW': 'Aruba',
  'AFG': 'Afghanistan',
  'AGO': 'Angola',
  'AIA': 'Anguilla',
  'ALA': 'Åland Islands',
  'ALB': 'Albania',
  'AND': 'Andorra',
  'ARE': 'United Arab Emirates',
  'ARG': 'Argentina',
  'ARM': 'Armenia',
  'ASM': 'Samoa',
  'ATA': 'Antarctica',
  'ATF': 'French Southern Territories',
  'ATG': 'Antigua and Barbuda',
  'AUS': 'Australia',
  'AUT': 'Austria',
  'AZE': 'Azerbaijan',
  'BDI': 'Burundi',
  'BEL': 'Belgium',
  'BEN': 'Benin',
  'BES': 'Bonaire',
  'BFA': 'Burkina',
  'BGD': 'Bangladesh',
  'BGR': 'Bulgaria',
  'BHR': 'Bahrain',
  'BHS': 'Bahamas',
  'BIH': 'Bosnia and Herzegovina',
  'BLM': 'Saint Barts',
  'BLR': 'Belarus',
  'BLZ': 'Belize',
  'BMU': 'Bermuda',
  'BOL': 'Bolivia',
  'BRA': 'Brazil',
  'BRB': 'Barbados',
  'BRN': 'Brunei',
  'BTN': 'Bhutan',
  'BVT': 'Bouvet Island',
  'BWA': 'Botswana',
  'CAF': 'Central African Republic',
  'CAN': 'Canada',
  'CCK': 'Cocos (Keeling) Islands',
  'CHE': 'Switzerland',
  'CHL': 'Chile',
  'CHN': 'China',
  'CIV': 'Ivory Coast',
  'CMR': 'Cameroon',
  'COD': 'Congo',
  'COG': 'Congo',
  'COK': 'Cook Islands',
  'COL': 'Colombia',
  'COM': 'Comoros',
  'CPV': 'Cape Verde',
  'CRI': 'Costa Rica',
  'CUB': 'Cuba',
  'CUW': 'Curacao',
  'CXR': 'Christmas Island',
  'CYM': 'Cayman Islands',
  'CYP': 'Cyprus',
  'CZE': 'Czechia',
  'DEU': 'Germany',
  'DJI': 'Djibouti',
  'DMA': 'Dominica',
  'DNK': 'Denmark',
  'DOM': 'Dominican Republic',
  'DZA': 'Algeria',
  'ECU': 'Ecuador',
  'EGY': 'Egypt',
  'ERI': 'Eritrea',
  'ESH': 'Western Sahara',
  'ESP': 'Spain',
  'EST': 'Estonia',
  'ETH': 'Ethiopia',
  'FIN': 'Finland',
  'FJI': 'Fiji',
  'FLK': 'Falkland Islands',
  'FRA': 'France',
  'FRO': 'Faroe Islands',
  'FSM': 'Micronesia',
  'GAB': 'Gabon',
  'GBR': 'United Kingdom',
  'GEO': 'Georgia',
  'GGY': 'Guernsey',
  'GHA': 'Ghana',
  'GIB': 'Gibraltar',
  'GIN': 'Guinea',
  'GLP': 'Guadeloupe',
  'GMB': 'Gambia',
  'GNB': 'Guinea-Bissau',
  'GNQ': 'Equatorial Guinea',
  'GRC': 'Greece',
  'GRD': 'Grenada',
  'GRL': 'Greenland',
  'GTM': 'Guatemala',
  'GUF': 'French Guiana',
  'GUM': 'Guam',
  'GUY': 'Guyana',
  'HKG': 'Hong Kong',
  'HMD': 'Australia',
  'HND': 'Honduras',
  'HRV': 'Croatia',
  'HTI': 'Haiti',
  'HUN': 'Hungary',
  'IDN': 'Indonesia',
  'IMN': 'Isle of Man',
  'IND': 'India',
  'IOT': 'British Indian Ocean Territory',
  'IRL': 'Ireland',
  'IRN': 'Iran',
  'IRQ': 'Iraq',
  'ISL': 'Iceland',
  'ISR': 'Israel',
  'ITA': 'Italy',
  'JAM': 'Jamaica',
  'JEY': 'Jersey',
  'JOR': 'Jordan',
  'JPN': 'Japan',
  'KAZ': 'Kazakhstan',
  'KEN': 'Kenya',
  'KGZ': 'Kyrgyzstan',
  'KHM': 'Cambodia',
  'KIR': 'Kiribati',
  'KNA': 'Saint Kitts and Nevis',
  'KOR': 'South Korea',
  'KWT': 'Kuwait',
  'LAO': 'Laos',
  'LBN': 'Lebanon',
  'LBR': 'Liberia',
  'LBY': 'Libya',
  'LCA': 'Saint Lucia',
  'LIE': 'Liechtenstein',
  'LKA': 'Sri Lanka',
  'LSO': 'Lesotho',
  'LTU': 'Lithuania',
  'LUX': 'Luxembourg',
  'LVA': 'Latvia',
  'MAC': 'Macao',
  'MAF': 'Saint Martin',
  'MAR': 'Morocco',
  'MCO': 'Monaco',
  'MDA': 'Moldova',
  'MDG': 'Madagascar',
  'MDV': 'Maldives',
  'MEX': 'Mexico',
  'MHL': 'Marshall Islands',
  'MKD': 'Macedonia',
  'MLI': 'Mali',
  'MLT': 'Malta',
  'MMR': 'Myanmar',
  'MNE': 'Montenegro',
  'MNG': 'Mongolia',
  'MNP': 'Northern Mariana Islands',
  'MOZ': 'Mozambique',
  'MRT': 'Mauritania',
  'MSR': 'Montserrat',
  'MTQ': 'Martinique',
  'MUS': 'Mauritius',
  'MWI': 'Malawi',
  'MYS': 'Malaysia',
  'MYT': 'Mayotte',
  'NAM': 'Namibia',
  'NCL': 'New Caledonia',
  'NER': 'Niger',
  'NFK': 'Norfolk Island',
  'NGA': 'Nigeria',
  'NIC': 'Nicaragua',
  'NIU': 'Niue',
  'NLD': 'Netherlands',
  'NOR': 'Norway',
  'NPL': 'Nepal',
  'NRU': 'Nauru',
  'NZL': 'New Zealand',
  'OMN': 'Oman',
  'PAK': 'Pakistan',
  'PAN': 'Panama',
  'PCN': 'United Kingdom',
  'PER': 'Peru',
  'PHL': 'Philippines',
  'PLW': 'Palau',
  'PNG': 'Papua New Guinea',
  'POL': 'Poland',
  'PRI': 'United States',
  'PRK': 'South Korea',
  'PRT': 'Portugal',
  'PRY': 'Paraguay',
  'PSE': 'Palestine',
  'PYF': 'French Polynesia',
  'QAT': 'Qatar',
  'REU': 'Reunion',
  'ROU': 'Romania',
  'RUS': 'Russia',
  'RWA': 'Rwanda',
  'SAU': 'Saudi Arabia',
  'SDN': 'Sudan',
  'SEN': 'Senegal',
  'SGP': 'Singapore',
  'SGS': 'South Georgia and the South Sandwich Islands',
  'SHN': 'Saint Helena',
  'SJM': 'Norway',
  'SLB': 'Solomon Islands',
  'SLE': 'Sierra Leone',
  'SLV': 'El Salvador',
  'SMR': 'San Marino',
  'SOM': 'Somalia',
  'SPM': 'Saint Pierre and Miquelon',
  'SRB': 'Serbia',
  'SSD': 'South Sudan',
  'STP': 'Sao Tome and Principe',
  'SUR': 'Suriname',
  'SVK': 'Slovakia',
  'SVN': 'Slovenia',
  'SWE': 'Sweden',
  'SWZ': 'Swaziland',
  'SXM': 'Saint Martin',
  'SYC': 'Seychelles',
  'SYR': 'Syria',
  'TCA': 'Turks & Caicos',
  'TCD': 'Chad',
  'TGO': 'Togo',
  'THA': 'Thailand',
  'TJK': 'Tajikistan',
  'TKL': 'Tokelau',
  'TKM': 'Turkmenistan',
  'TLS': 'East Timor',
  'TON': 'Tonga',
  'TTO': 'Trinidad and Tobago',
  'TUN': 'Tunisia',
  'TUR': 'Turkey',
  'TUV': 'Tuvalu',
  'TWN': 'Taiwan',
  'TZA': 'Tanzania',
  'UGA': 'Uganda',
  'UKR': 'Ukraine',
  'UMI': 'United States',
  'URY': 'Uruguay',
  'USA': 'United States',
  'UZB': 'Uzbekistan',
  'VAT': 'Vatican City',
  'VCT': 'Saint Vincent and the Grenadines',
  'VEN': 'Venezuela',
  'VGB': 'US Virgin Islands',
  'VIR': 'US Virgin Islands',
  'VNM': 'Vietnam',
  'VUT': 'Vanuatu',
  'WLF': 'France',
  'WSM': 'Samoa',
  'YEM': 'Yemen',
  'ZAF': 'South Africa',
  'ZMB': 'Zambia',
  'ZWE': 'Zimbabwe',
  'UK': 'United Kingdom',
  'RUSSIAN FEDERATION': 'Russia',
  'KOREA': 'South Korea',
  'IRAN (ISLAMIC REPUBLIC OF)': 'Iran',
  'MACAU': 'Macao',
  'MOLDOVA, REPUBLIC OF': 'Moldova',
  'REUNION ISLAND': 'Reunion',
  'TURKS AND CAICOS ISLANDS': 'Turks & Caicos',
  'VIRGIN ISLANDS (BRITISH)': 'British US Virgin Islands',
  'VIRGIN ISLANDS (USA)': 'US Virgin Islands',
  'PUERTO RICO': 'United States',
  'EL': 'Greece',
  'SINT MAARTEN': 'Saint Martin',
  'CROATIA/HRVATSKA': 'Croatia',
  'LAO PEOPLES DEMOCRATIC REPUBLIC': 'Laos',
  'GUAM (USA)': 'Guam',
  'ENGLAND': 'United Kingdom',
  'FWI': 'French West Indies',
  'GEORGIA, REPUBLIC OF': 'Georgia',
  'USVI': 'US Virgin Islands',
  'U.S.A.': 'United States',
  'KINGDOM OF SAUDI ARABIA': 'Saudi Arabia',
  'TRINIDAD': 'Trinidad and Tobago',
  'US VI': 'US Virgin Islands',
  'BRASIL': 'Brazil',
  'KOREA, REPUBLIC OF': 'South Korea',
  'AMERICAN SAMOA': 'Samoa',
  'BURKINA FASO': 'Burkina',
  'BRUNEI DARUSSALAM': 'Brunei',
  'CABO VERDE': 'Cape Verde',
  'CZECHIA': 'Czech Republic',
  'FALKLAND ISLANDS (MALVINAS)': 'Falkland Islands',
  'HEARD ISLAND AND MCDONALD ISLANDS': 'Australia',
  'LAO PEOPLE\'S DEMOCRATIC REPUBLIC': 'Laos',
  'SAINT MARTIN (FRENCH PART)': 'Saint Martin',
  'PITCAIRN': 'United Kingdom',
  'SVALBARD AND JAN MAYEN': 'Norway',
  'SINT MAARTEN (DUTCH PART)': 'Saint Martin',
  'SYRIAN ARAB REPUBLIC': 'Syria',
  'TIMOR-LESTE': 'East Timor',
  'UNITED STATES MINOR OUTLYING ISLANDS': 'United States',
  'HOLY SEE (VATICAN CITY STATE)': 'Vatican City',
  'VIRGIN ISLANDS': 'US Virgin Islands',
  'WALLIS AND FUTUNA': 'France',
  'ARUBA': 'Aruba',
  'AFGHANISTAN': 'Afghanistan',
  'ANGOLA': 'Angola',
  'ANGUILLA': 'Anguilla',
  'ÅLAND ISLANDS': 'Åland Islands',
  'ALBANIA': 'Albania',
  'ANDORRA': 'Andorra',
  'UNITED ARAB EMIRATES': 'United Arab Emirates',
  'ARGENTINA': 'Argentina',
  'ARMENIA': 'Armenia',
  'SAMOA': 'Samoa',
  'ANTARCTICA': 'Antarctica',
  'FRENCH SOUTHERN TERRITORIES': 'French Southern Territories',
  'ANTIGUA AND BARBUDA': 'Antigua and Barbuda',
  'AUSTRALIA': 'Australia',
  'AUSTRIA': 'Austria',
  'AZERBAIJAN': 'Azerbaijan',
  'BURUNDI': 'Burundi',
  'BELGIUM': 'Belgium',
  'BENIN': 'Benin',
  'BONAIRE': 'Bonaire',
  'BURKINA': 'Burkina',
  'BANGLADESH': 'Bangladesh',
  'BULGARIA': 'Bulgaria',
  'BAHRAIN': 'Bahrain',
  'BAHAMAS': 'Bahamas',
  'BOSNIA AND HERZEGOVINA': 'Bosnia and Herzegovina',
  'SAINT BARTS': 'Saint Barts',
  'BELARUS': 'Belarus',
  'BELIZE': 'Belize',
  'BERMUDA': 'Bermuda',
  'BOLIVIA': 'Bolivia',
  'BRAZIL': 'Brazil',
  'BARBADOS': 'Barbados',
  'BRUNEI': 'Brunei',
  'BHUTAN': 'Bhutan',
  'BOUVET ISLAND': 'Bouvet Island',
  'BOTSWANA': 'Botswana',
  'CENTRAL AFRICAN REPUBLIC': 'Central African Republic',
  'CANADA': 'Canada',
  'COCOS (KEELING) ISLANDS': 'Cocos (Keeling) Islands',
  'SWITZERLAND': 'Switzerland',
  'CHILE': 'Chile',
  'CHINA': 'China',
  'IVORY COAST': 'Ivory Coast',
  'CAMEROON': 'Cameroon',
  'CONGO': 'Congo',
  'COOK ISLANDS': 'Cook Islands',
  'COLOMBIA': 'Colombia',
  'COMOROS': 'Comoros',
  'CAPE VERDE': 'Cape Verde',
  'COSTA RICA': 'Costa Rica',
  'CUBA': 'Cuba',
  'CURACAO': 'Curacao',
  'CHRISTMAS ISLAND': 'Christmas Island',
  'CAYMAN ISLANDS': 'Cayman Islands',
  'CYPRUS': 'Cyprus',
  'CZECHIA': 'Czechia',
  'GERMANY': 'Germany',
  'DJIBOUTI': 'Djibouti',
  'DOMINICA': 'Dominica',
  'DENMARK': 'Denmark',
  'DOMINICAN REPUBLIC': 'Dominican Republic',
  'ALGERIA': 'Algeria',
  'ECUADOR': 'Ecuador',
  'EGYPT': 'Egypt',
  'ERITREA': 'Eritrea',
  'WESTERN SAHARA': 'Western Sahara',
  'SPAIN': 'Spain',
  'ESTONIA': 'Estonia',
  'ETHIOPIA': 'Ethiopia',
  'FINLAND': 'Finland',
  'FIJI': 'Fiji',
  'FALKLAND ISLANDS': 'Falkland Islands',
  'FRANCE': 'France',
  'FAROE ISLANDS': 'Faroe Islands',
  'MICRONESIA': 'Micronesia',
  'GABON': 'Gabon',
  'UNITED KINGDOM': 'United Kingdom',
  'GEORGIA': 'Georgia',
  'GUERNSEY': 'Guernsey',
  'GHANA': 'Ghana',
  'GIBRALTAR': 'Gibraltar',
  'GUINEA': 'Guinea',
  'GUADELOUPE': 'Guadeloupe',
  'GAMBIA': 'Gambia',
  'GUINEA-BISSAU': 'Guinea-Bissau',
  'EQUATORIAL GUINEA': 'Equatorial Guinea',
  'GREECE': 'Greece',
  'GRENADA': 'Grenada',
  'GREENLAND': 'Greenland',
  'GUATEMALA': 'Guatemala',
  'FRENCH GUIANA': 'French Guiana',
  'GUAM': 'Guam',
  'GUYANA': 'Guyana',
  'HONG KONG': 'Hong Kong',
  'HONDURAS': 'Honduras',
  'CROATIA': 'Croatia',
  'HAITI': 'Haiti',
  'HUNGARY': 'Hungary',
  'INDONESIA': 'Indonesia',
  'ISLE OF MAN': 'Isle of Man',
  'INDIA': 'India',
  'BRITISH INDIAN OCEAN TERRITORY': 'British Indian Ocean Territory',
  'IRELAND': 'Ireland',
  'IRAN': 'Iran',
  'IRAQ': 'Iraq',
  'ICELAND': 'Iceland',
  'ISRAEL': 'Israel',
  'ITALY': 'Italy',
  'JAMAICA': 'Jamaica',
  'JERSEY': 'Jersey',
  'JORDAN': 'Jordan',
  'JAPAN': 'Japan',
  'KAZAKHSTAN': 'Kazakhstan',
  'KENYA': 'Kenya',
  'KYRGYZSTAN': 'Kyrgyzstan',
  'CAMBODIA': 'Cambodia',
  'KIRIBATI': 'Kiribati',
  'SAINT KITTS AND NEVIS': 'Saint Kitts and Nevis',
  'SOUTH KOREA': 'South Korea',
  'KUWAIT': 'Kuwait',
  'LAOS': 'Laos',
  'LEBANON': 'Lebanon',
  'LIBERIA': 'Liberia',
  'LIBYA': 'Libya',
  'SAINT LUCIA': 'Saint Lucia',
  'LIECHTENSTEIN': 'Liechtenstein',
  'SRI LANKA': 'Sri Lanka',
  'LESOTHO': 'Lesotho',
  'LITHUANIA': 'Lithuania',
  'LUXEMBOURG': 'Luxembourg',
  'LATVIA': 'Latvia',
  'MACAO': 'Macao',
  'SAINT MARTIN': 'Saint Martin',
  'MOROCCO': 'Morocco',
  'MONACO': 'Monaco',
  'MOLDOVA': 'Moldova',
  'MADAGASCAR': 'Madagascar',
  'MALDIVES': 'Maldives',
  'MEXICO': 'Mexico',
  'MARSHALL ISLANDS': 'Marshall Islands',
  'MACEDONIA': 'Macedonia',
  'MALI': 'Mali',
  'MALTA': 'Malta',
  'MYANMAR': 'Myanmar',
  'MONTENEGRO': 'Montenegro',
  'MONGOLIA': 'Mongolia',
  'NORTHERN MARIANA ISLANDS': 'Northern Mariana Islands',
  'MOZAMBIQUE': 'Mozambique',
  'MAURITANIA': 'Mauritania',
  'MONTSERRAT': 'Montserrat',
  'MARTINIQUE': 'Martinique',
  'MAURITIUS': 'Mauritius',
  'MALAWI': 'Malawi',
  'MALAYSIA': 'Malaysia',
  'MAYOTTE': 'Mayotte',
  'NAMIBIA': 'Namibia',
  'NEW CALEDONIA': 'New Caledonia',
  'NIGER': 'Niger',
  'NORFOLK ISLAND': 'Norfolk Island',
  'NIGERIA': 'Nigeria',
  'NICARAGUA': 'Nicaragua',
  'NIUE': 'Niue',
  'NETHERLANDS': 'Netherlands',
  'NORWAY': 'Norway',
  'NEPAL': 'Nepal',
  'NAURU': 'Nauru',
  'NEW ZEALAND': 'New Zealand',
  'OMAN': 'Oman',
  'PAKISTAN': 'Pakistan',
  'PANAMA': 'Panama',
  'PERU': 'Peru',
  'PHILIPPINES': 'Philippines',
  'PALAU': 'Palau',
  'PAPUA NEW GUINEA': 'Papua New Guinea',
  'POLAND': 'Poland',
  'UNITED STATES': 'United States',
  'PORTUGAL': 'Portugal',
  'PARAGUAY': 'Paraguay',
  'PALESTINE': 'Palestine',
  'FRENCH POLYNESIA': 'French Polynesia',
  'QATAR': 'Qatar',
  'REUNION': 'Reunion',
  'ROMANIA': 'Romania',
  'RUSSIA': 'Russia',
  'RWANDA': 'Rwanda',
  'SAUDI ARABIA': 'Saudi Arabia',
  'SUDAN': 'Sudan',
  'SENEGAL': 'Senegal',
  'SINGAPORE': 'Singapore',
  'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS': 'South Georgia and the South Sandwich Islands',
  'SAINT HELENA': 'Saint Helena',
  'SOLOMON ISLANDS': 'Solomon Islands',
  'SIERRA LEONE': 'Sierra Leone',
  'EL SALVADOR': 'El Salvador',
  'SAN MARINO': 'San Marino',
  'SOMALIA': 'Somalia',
  'SAINT PIERRE AND MIQUELON': 'Saint Pierre and Miquelon',
  'SERBIA': 'Serbia',
  'SOUTH SUDAN': 'South Sudan',
  'SAO TOME AND PRINCIPE': 'Sao Tome and Principe',
  'SURINAME': 'Suriname',
  'SLOVAKIA': 'Slovakia',
  'SLOVENIA': 'Slovenia',
  'SWEDEN': 'Sweden',
  'SWAZILAND': 'Swaziland',
  'SEYCHELLES': 'Seychelles',
  'SYRIA': 'Syria',
  'TURKS & CAICOS': 'Turks & Caicos',
  'CHAD': 'Chad',
  'TOGO': 'Togo',
  'THAILAND': 'Thailand',
  'TAJIKISTAN': 'Tajikistan',
  'TOKELAU': 'Tokelau',
  'TURKMENISTAN': 'Turkmenistan',
  'EAST TIMOR': 'East Timor',
  'TONGA': 'Tonga',
  'TRINIDAD AND TOBAGO': 'Trinidad and Tobago',
  'TUNISIA': 'Tunisia',
  'TURKEY': 'Turkey',
  'TUVALU': 'Tuvalu',
  'TAIWAN': 'Taiwan',
  'TANZANIA': 'Tanzania',
  'UGANDA': 'Uganda',
  'UKRAINE': 'Ukraine',
  'URUGUAY': 'Uruguay',
  'UZBEKISTAN': 'Uzbekistan',
  'VATICAN CITY': 'Vatican City',
  'SAINT VINCENT AND THE GRENADINES': 'Saint Vincent and the Grenadines',
  'VENEZUELA': 'Venezuela',
  'US VIRGIN ISLANDS': 'US Virgin Islands',
  'VIETNAM': 'Vietnam',
  'VANUATU': 'Vanuatu',
  'YEMEN': 'Yemen',
  'SOUTH AFRICA': 'South Africa',
  'ZAMBIA': 'Zambia',
  'ZIMBABWE': 'Zimbabwe',
  'BRITISH US VIRGIN ISLANDS': 'British US Virgin Islands',
  'US Virgin Islands': 'US Virgin Islands',
  'FRENCH WEST INDIES': 'French West Indies',
  'CZECH REPUBLIC': 'Czech Republic',
  'ETATS UNIS': 'United States',
  'ITALIA': 'Italy'
}


# Normalise by lowering case to avoid case sensitivity related issues...
country_dict = {k.lower(): v for k, v in country_dict.items()}